#!/bin/bash

if [ ! -d wolfssl ]; then
  echo "info: cloning wolfssl"
  git clone https://github.com/philljj/wolfssl.git || exit 1
fi

cd wolfssl || exit 1

if [ ! -f configure ]; then
  ./autogen.sh || exit 1
fi

if [ $# -eq 1 ]; then
  echo "info: full rebuild"
  if [ -f configure ]; then
    rm configure
    autoreconf
  fi
fi

./configure \
  --enable-acert \
  --enable-debug \
  --enable-opensslextra \
  --enable-rsapss \
  CFLAGS="-DWOLFSSL_DEBUG_ASN_TEMPLATE -DWOLFSSL_PUBLIC_ASN" \
  || exit 1
make || exit 1
sudo make install
