#!/bin/bash
cd wolfssl || exit 1

if [ $# -eq 1 ]; then
  echo "info: full rebuild"
  if [ -f configure ]; then
    rm configure
    autoreconf
  fi
fi

./configure \
  --enable-acert \
  --enable-debug \
  --enable-opensslextra \
  --enable-rsapss \
  CFLAGS="-DWOLFSSL_DEBUG_ASN_TEMPLATE -DWOLFSSL_PUBLIC_ASN" \
  || exit 1
make || exit 1
sudo make install
