#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

function run_test {
  if ./test/test_acert -f $1 > /dev/null ; then
    echo -e "info: $1: ${GREEN}pass${NC}"
  else
    echo -e "error: $1: ${RED}fail${NC}"
    exit 1
  fi
}

./scripts/test/build_test || exit 1

for acert in "certs/acert.pem" \
             "certs/acert_ietf.pem" \
             "certs/acert_bc2.pem" \
             "certs/signed/rsa_pss/acert.pem" \
             "certs/signed/rsa_pss/acert_ietf.pem" \
             "certs/signed/rsa_pss/acert_bc2.pem" ; do
  run_test $acert
done

echo ""

./scripts/test/build_test wolf || exit 1

for acert in "certs/acert.pem" \
             "certs/acert_ietf.pem" \
             "certs/acert_bc2.pem" \
             "certs/signed/rsa_pss/acert.pem" \
             "certs/signed/rsa_pss/acert_ietf.pem" \
             "certs/signed/rsa_pss/acert_bc2.pem"; do
  run_test $acert
done
