#!/bin/bash

RED='\033[1;31m'
GREEN='\033[1;32m'
NC='\033[0m'

function err_and_die {
  echo -e "error: $1: ${RED}fail${NC}"
  exit 1
}

acert="certs/acert.pem"

for salt in 1 10 20 30; do
  # build against openssl
  if ! ./scripts/test/build_test > /dev/null; then
    err_and_die "build_test: $acert"
  fi

  if ! ./test/test_acert -f $acert -srw -l $salt > /dev/null 2>&1; then
    err_and_die "test_acert -f -srw -l $salt: $acert"
  fi

  echo "  info: test_acert sign verify: $salt: good"

  # Now test verification with newly signed cert and key.
  if ! ./test/test_acert -f acert_new.pem -k pkey_new.pem > /dev/null ; then
    err_and_die "test_acert -k: $salt"
  fi

  echo "  info: test_acert read verify: $salt: good"

  # Now rebuild against wolfssl...
  if ! ./scripts/test/build_test wolf  > /dev/null; then
    err_and_die "build_test wolf: $salt"
  fi

  # ... and repeat test.
  if ! ./test/test_acert -f acert_new.pem -k pkey_new.pem > /dev/null ; then
    err_and_die "test_acert -f -k (wolf): $salt"
  fi

  echo "  info: test_acert read verify (wolf): $salt: good"

  echo -e "info: $acert: ${GREEN}pass${NC}"
  echo ""
done
